### ISSUE TITLE
Make `pse::String` and `pse::StringList` in different header files.

### ISSUE THREAD

**Issue by robertshepherdcpp** [robertshepherdcpp/pse#8]
There is nothing much more to say. `pse::String` and `pse::StringList` are found in different header files but i think that they should be in different header files. But bear in mind that any programs that use `pse::StringList` will need to include the new `StringList.cpp` header file. The name should be `pse::StringList`.

**Comment by ryuusama09** [comment]
linking the pr to this issue https://github.com/robertshepherdcpp/pse/pull/10

**Comment by robertshepherdcpp** [comment]
This issue has been succesfully resolved by ryuusama09 in commit https://github.com/robertshepherdcpp/pse/pull/10!
